### ISSUE TITLE
Timestamp for Max8

### ISSUE THREAD

**Issue by KaneBetter** [omarcostahamido/PVM#35]
We test two RPIs in the classroom.
Found out that Max8 command for each rpi is not at the same time.
There is a 0.5s delay between two rpis.

We want Max8 can send out commands like this: start 18:00:00(current time).
You can see the video in slack https://swe276pcapsto-5ba9154.slack.com/files/U043JMJPPQE/F0490JZ97GF/img_0585.mov

**Comment by KaneBetter** [comment]
We have confirmed that MAX does run pvm_send at the same time.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/37838032/200143520-0dac5142-8137-4cce-af52-f4cc6d08c05d.png">

So the cause of the delay must be inside the UDP send process.

**Comment by KaneBetter** [comment]
With this new pvm_send, our solution will become very simple, send the current time by UDP, then all RPI receive the time and postpone the operation backward for 3s to solve the synchronization problem perfectly.

**Comment by KaneBetter** [comment]
Pushed branch https://github.com/omarcostahamido/PVM/tree/AddTimeInUDP
and rewrite the python script to parse the time.

**Comment by omarcostahamido** [comment]
> There is a 0.5s delay between two rpis.

Oh no...

> We have confirmed that MAX does run pvm_send at the same time.
So the cause of the delay must be inside the UDP send process.

Creating a new UDP object would be quite the achievement, not impossible though. I've done one [here](https://github.com/omarcostahamido/One-Quick-Solution/tree/master/MaxMsp/och.udp). Never tested against the default one in max for performance though. I built it in order to easily receive the IP+port of the sender in the received end.

> With this new pvm_send, our solution will become very simple, send the current time by UDP, then all RPI receive the time and postpone the operation backward for 3s to solve the synchronization problem perfectly.

Oh interesting... you know, this is now starting to remind me more about [Ableton Link](https://github.com/Ableton/link) that is a technology aimed at solving this exact problem of synchroization across different audio applications, and Max has a [Link package](https://cycling74.com/feature/abletonlink) too! (which I never really got much deep into it). Food for thought, or just another possible elegant solution?

> Pushed branch

will check this out
