### ISSUE TITLE
the `loadbang` problem

### ISSUE THREAD

**Issue by omarcostahamido** [omarcostahamido/PVM#68]
According to the PIP team, the `loadbang` in the max patch creates a conflict with `pvm.py`.
And this was, apparently, the reason behind the mysterious #66 ...
This "fix" seems cumbersome, and it leads to an immediate problem which is that users need to send the `file` command twice in order for it to be registered by the RPI devices after `pvm.py` is launched.

@rustberry and @SSSSam141 gave an example scenario where the user needs to reset the Max patch, and this will cause the videos currently playing to be stopped. This is a good enough reason to remove the `loadbang`. And also, [this](https://github.com/omarcostahamido/PVM/blame/71f3bbab073ca13658e66037226b5492abf4025f/pvm.py#L84) line from #67 is addressing this second (?) problem too.

**TODO**
- [x] remove `loadbang` from max patch
- [x] remove `COUNT`
- [ ] verify that the problem is fixed

**Comment by rustberry** [comment]
Hi @omarcostahamido, sry for the late reply, have been busy with interviewing and capstone stuff. Submitted a commit to revert `COUNT` in #69. Glad to see you also agree to remove `loadbang`. You are correct that with #67 [line 84](https://github.com/omarcostahamido/PVM/pull/67/files#diff-b4823c6c09e6236e75beb51391891593c4f1f6a6f3f529b393e14f87157b6331R84), the problem of the same video file being reset when the Max patch is restarted is fixed. But I still believe that removing `loadbang` is useful in order to avoid future conflicts.
