### ISSUE TITLE
Setting up SSH access to studio (if possible)

### ISSUE THREAD

**Issue by rustberry** [omarcostahamido/PVM#9]
When in the later stage we need to test synchronization on multiple rpis, this would make it possible to test functionality on them remotely, rather than each one bringing one device home.

**Comment by omarcostahamido** [comment]
This refers to #6 .
Figuring out how to remotely access the rpis will be a priority thing because, as you will very soon realize the custom screens we are using for the installation don't display the entire desktop of the rpi OS. You can always connect it to another full monitor just to work on it, if they are available there. So yes please, we do need to have this remote access resolved. Let's keep it as it's own issue here, that can be assigned to one person right away, and link it as a todo list item on #6 .

**Comment by omarcostahamido** [comment]
So, @rustberry , what have you found out?

**Comment by rustberry** [comment]
It seems that RealVNC provides cloud connection for educational or non-commercial use. With this we would be able to set up VNC to the iMac in studio easily. And from that iMac we could ssh into the rest of the rpis in the studio's wifi.

On this Thursday I think I would be able to test this.

**Comment by rustberry** [comment]
@KaneBetter also discovered some free tools to do intranet penetration (https://www.cpolar.com/). If the RealVNC doesn't work we could fall back to this solution.

**Comment by omarcostahamido** [comment]
Yes, also just [found it](https://github.com/omarcostahamido/PVM/blame/main/README.md#L99) again on the #Helpful Links section.

**Comment by omarcostahamido** [comment]
@rustberry when do you think we can close this issue?

had a quick look at `cpolar`, it looks more like an http tunneling service, not a full blown remote desktop access (?).

**Comment by rustberry** [comment]
Yes you are right. With tunneling service we would be able to establish SSH connection to it. But since we need to see the video output, it would be better to use VNC or TeamViewer. On Thursday we set up VNC but discovered that it was hard to use when connecting from a different network (it requires everyone to have an account and be added to the same "team").

We then opened Teamviewer on it, but today we found ourselves unable to access it through teamviewer, probably because the iMac went dormant.

Next time we get to the studio we will change the settings on it and then this issue will be resolved and closed.

**Comment by omarcostahamido** [comment]
@rustberry you can also try [rustdesk](https://rustdesk.com/), as I've mentioned on #6 .
I don't think we need to spend a lot of time on this issue finding the perfect solution. Just having something that works will do. I mean, it is not an essential part of the final project in itself. Future users won't need to have a perfect ssh access in order to make the project work. I have this issue as high priority just because I'd like for this to be closed soon, so we can move on to more interesting problems 😄

**Comment by rustberry** [comment]
Yes totally understand. Actually, TeamViewer has already solved this problem, I left this open only because I think we need to set the iMac dormant settings to mark this problem as _completely_ solved 😃. While this remains open I have been moving on to do other tasks like compiling vlc source code, reading vlc logs, and testing OXMPlayer, so this issue never hindered me from doing other things.

**Comment by rustberry** [comment]
The TeamViewer logins are now in our slack, closing.
